# Generated by Django 4.0.1 on 2022-01-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cost',
            name='closed_by',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='cost',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cost',
            name='created_by',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='cost',
            name='reviewers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cost',
            name='status',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cost',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cost',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cost',
            name='subject',
            field=models.CharField(default='', max_length=512),
        ),
    ]
