# Generated by Django 4.0.1 on 2022-01-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cost_amount_cost_closed_by_cost_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='closed_by',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='cost',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cost',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cost',
            name='reviewers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cost',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
