# Generated by Django 4.0.1 on 2022-01-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_cost_closed_by_alter_cost_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='attachments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
