# Generated by Django 4.0.1 on 2022-02-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_vendorsubsidiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='expense_account',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='cost',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='cost',
            name='subsidiary',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='cost',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
