# Generated by Django 4.0.1 on 2022-04-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_price_myapp_price_product_5f2b26_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='flag',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
