# Generated by Django 4.0.1 on 2022-06-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_price_latest_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wayfair_sku',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='home_depot_item_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model'], name='myapp_produ_model_af8b7c_idx'),
        ),
    ]
