# Generated by Django 4.0.1 on 2022-07-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_product_wayfair_sku_alter_product_home_depot_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wayfair_option_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
